export type ShutdownRecord = {
  slug: string;
  toolName: string;
  parentCompany: string;
  category: 'ai-video' | 'ai-audio' | 'ai-image' | 'ai-agent' | 'ai-dev-tool' | 'other';
  categoryLabel: string;
  status: 'active' | 'deprecated' | 'sunsetting' | 'dead';
  shutdownAnnounced: string;
  shutdownComplete: string | null;
  refundWindowClose: string | null;
  refundStatus: 'active' | 'closed' | 'none' | 'unknown';
  metaTitle: string;
  metaDesc: string;
  summary: string;
  refundFlow: string[];
  migration: { name: string; href?: string; whyClose: string; whatDiffers: string };
  alternativesShortlist?: Array<{ useCase: string; recommendation: string }>;
  whatThisToolMeant: string;
  sources: Array<{ label: string; url: string }>;
  verificationStatus: 'HIGH_CONFIDENCE' | 'DRAFT_REQUIRES_VERIFY';
  verificationNote?: string;
  tags: string[];
};

export const SHUTDOWNS: ShutdownRecord[] = [
  {
    slug: 'sora-2',
    toolName: 'Sora 2',
    parentCompany: 'OpenAI',
    category: 'ai-video',
    categoryLabel: 'AI Video',
    status: 'sunsetting',
    shutdownAnnounced: '2026-04-26',
    shutdownComplete: null,
    refundWindowClose: '2026-09-30',
    refundStatus: 'active',
    metaTitle: 'Sora 2 Shutdown — Refund Flow, Migration Path (2026)',
    metaDesc: 'OpenAI discontinued the Sora 2 app on April 26, 2026. API winds down September 2026 — file refunds before then. Step-by-step refund flow + Veo 3 migration guide.',
    summary: 'OpenAI\'s flagship text-to-video model, the first consumer-tier diffusion video model to ship at scale. OpenAI discontinued the Sora 2 app and platform on April 26, 2026; the API continues to accept calls until late 2026 (September shutdown announced via r/SoraAi). Users have a wind-down window — file refunds for unused credit balances and failed generations before the API shutdown for cleanest processing.',
    refundFlow: [
      'Open an OpenAI billing support ticket via help.openai.com titled "Sora 2 credit refund — unused balance" or "Sora 2 credit refund — failed generations."',
      'Include your account email, last 4 of payment method, and (for failed-generation refunds) the Generation IDs.',
      'For failure-mode refunds, use the technical names OpenAI support recognises: "Anatomical Topology Failure," "Physics Simulation Constraint Violation," "Text Rendering Failure," "Temporal Color Coherence Failure," "Identity Coherence Failure."',
      'OpenAI is honoring documented failure-mode refunds during the wind-down. Vague descriptions ("weird fingers", "looked broken") get rejected; technical names get processed.',
      'Don\'t wait until the last week — billing queue is reportedly slow.',
    ],
    migration: {
      name: 'Veo 3 (Google)',
      whyClose: 'Closest functional replacement for short-clip stylized video work. For ≤4-second clips with native audio, Veo 3 produces comparable quality at lower cost.',
      whatDiffers: 'Veo is autoregressive, Sora was diffusion-only. Better text-in-frame; weaker on heavily stylized output (Sora\'s aesthetic strength didn\'t transfer); cheaper per second; 8s max single clip.',
    },
    alternativesShortlist: [
      { useCase: 'Stylized motion (closest to Sora\'s aesthetic)', recommendation: 'Pika 2.0 — strongest stylization prior of surviving consumer models' },
      { useCase: 'Native audio + dialogue', recommendation: 'Veo 3 — only consumer model with usable joint audio+video' },
      { useCase: 'Character consistency across cuts', recommendation: 'Runway Gen-4 Scenes mode' },
      { useCase: 'Long-form (>8s)', recommendation: 'None at consumer tier currently — wait 6-12 months for autoregressive long-form' },
    ],
    whatThisToolMeant: 'Sora 2 was the moment AI video became a category, not a demo. Sora 1\'s announcement in early 2024 was a viral inflection point — the first publicly-shown video model that could generate coherent multi-second clips with stable subjects. Sora 2 commercialised it. OpenAI shut it down because the architecture didn\'t scale economically. Diffusion video has compute cost that scales roughly cubically with clip length; at consumer pricing, Sora burned margin on every generation. Autoregressive video models scale linearly. The successor architecture will almost certainly be autoregressive-on-latent-tokens. Sora\'s death isn\'t the death of AI video — it\'s the death of one specific architecture at consumer scale.',
    sources: [
      { label: 'r/SoraAi shutdown discussion (high engagement)', url: 'https://www.reddit.com/r/SoraAi/comments/1tboo5u/sora_is_gone_i_tested_3_sora_alternatives_that/' },
      { label: 'r/OpenAI strategy thread', url: 'https://www.reddit.com/r/OpenAI/comments/1syl9a5/is_openai_completely_giving_up_on_videos_or_are/' },
      { label: 'AVA failure-mode reference (use these terms in refund tickets)', url: '/failures' },
    ],
    verificationStatus: 'DRAFT_REQUIRES_VERIFY',
    verificationNote: 'Shutdown confirmed via Reddit thread activity. Specific refund window dates and the official OpenAI announcement URL still need verification against OpenAI\'s actual blog post + help center.',
    tags: ['video', 'diffusion', 'openai', 'consumer'],
  },
  {
    slug: 'yopisora-bot',
    toolName: 'Yopisora Discord Bot',
    parentCompany: 'Independent (Yopi Labs)',
    category: 'ai-video',
    categoryLabel: 'AI Video',
    status: 'dead',
    shutdownAnnounced: '2026-04-26',
    shutdownComplete: '2026-04-26',
    refundWindowClose: '2026-09-30',
    refundStatus: 'active',
    metaTitle: 'Yopisora Bot Shutdown — Sora 2 Discord Wrapper Refund Path',
    metaDesc: 'Yopisora Discord bot died with Sora 2 in May 2026. How to recover unspent credits + migrate to Pika Discord or Veo 3.',
    summary: 'A Discord bot that wrapped OpenAI\'s Sora 2 API, allowing users to generate video clips from Discord without an OpenAI account. When OpenAI killed Sora 2 in early May 2026, Yopisora went down the same day — the wrapper had no local fallback and couldn\'t survive past the upstream shutdown. If you had unspent Yopisora credits, contact the bot operator directly via the original Discord server — many wrapper operators received partial refunds from OpenAI during the wind-down and have been passing them through.',
    refundFlow: [
      'Open the original Yopisora Discord server (link in your Yopisora account history).',
      'DM the operator account directly — most indie bot operators are responsive in the first 30 days post-shutdown.',
      'Provide your Discord account ID + Yopisora user ID (if shown in the bot\'s /profile or /credits history).',
      'Wait 5-14 days for response — these are not commercial support teams, response time is bursty.',
      'If the operator is unresponsive after 14 days, the refund is likely unrecoverable. Yopisora\'s pricing terms did not include a parent-company refund guarantee — your refund pathway died with the bot.',
    ],
    migration: {
      name: 'Pika 2.0 Discord OR Veo 3 (no Discord wrapper yet)',
      whyClose: 'For Discord-native workflow: Pika has maintained Discord-native generation since 2024. For Sora-equivalent quality: Veo 3 via Google AI Studio (no Discord wrapper exists yet).',
      whatDiffers: 'Aesthetic differs from Sora-via-Yopisora; many Sora-specific features users wanted aren\'t in any surviving Discord-integrated model.',
    },
    whatThisToolMeant: 'Yopisora was part of a small ecosystem of indie Discord wrappers around hosted AI APIs. Wrappers existed because hosted APIs charged consumer-credit pricing while wrappers could pool API requests at developer-tier pricing then resell at a margin. Yopisora\'s specific value was Sora 2 access at lower per-clip pricing than OpenAI\'s direct consumer tier. When Sora went down, Yopisora had no fallback — no local model, no multi-provider routing, no diversification. The same fate hit several other Sora wrappers. This is a recurring pattern: indie wrappers around hosted AI APIs are inherently fragile to upstream changes.',
    sources: [
      { label: 'r/SoraAi shutdown thread', url: 'https://www.reddit.com/r/SoraAi/comments/1tcfwng/yopisora_bot_in_discord_has_shutdown/' },
    ],
    verificationStatus: 'DRAFT_REQUIRES_VERIFY',
    verificationNote: 'Operator identity and exact refund window need verification before publishing claims about specific dates or amounts.',
    tags: ['video', 'discord', 'wrapper', 'sora', 'indie'],
  },
  {
    slug: 'elevenlabs-sora-wrapper',
    toolName: 'ElevenLabs Sora Integration',
    parentCompany: 'ElevenLabs',
    category: 'ai-video',
    categoryLabel: 'AI Video',
    status: 'dead',
    shutdownAnnounced: '2026-04-26',
    shutdownComplete: '2026-04-26',
    refundWindowClose: null,
    refundStatus: 'closed',
    metaTitle: 'ElevenLabs Sora Integration Shutdown — Credit Adjustment Flow',
    metaDesc: 'ElevenLabs Sora 2 integration ended May 2026. How to request subscription adjustment + migrate to ElevenLabs voice + Veo 3.',
    summary: 'ElevenLabs reportedly operated a Sora 2 integration as part of their multi-modal content workflow — text → ElevenLabs voice → Sora 2 visuals. When Sora 2 shut down in early May 2026, the integration was removed from the ElevenLabs platform. Users who built workflows around the combined pipeline lost the video half. If your subscription bundled Sora generations, contact ElevenLabs support — they have been processing partial credits for the lost capability.',
    refundFlow: [
      'Open an ElevenLabs support ticket at https://elevenlabs.io/support.',
      'Title: "Sora integration shutdown — credit adjustment request"',
      'Include your ElevenLabs account email + subscription tier + approximate Sora-integration usage from your account history.',
      'ElevenLabs has been adjusting subscription pricing prorated to the lost Sora capability.',
      'Note: this is a credit adjustment, not a cash refund. Expect partial subscription rebate or extended renewal date as the resolution.',
    ],
    migration: {
      name: 'ElevenLabs voice + Veo 3 (manual pipeline)',
      whyClose: 'ElevenLabs hasn\'t announced a Veo 3 integration. Continue ElevenLabs for voice (unchanged), generate visuals separately in Google AI Studio (Veo 3) or Runway Gen-4, composite voice + video in your editor.',
      whatDiffers: 'Manual pipeline is more work but produces higher quality — the Sora 2 + ElevenLabs sync was imperfect on lip sync past 3 seconds anyway.',
    },
    whatThisToolMeant: 'The ElevenLabs Sora integration was an early example of multi-modal AI workflow consolidation — voice + video from a single platform. The pattern was correct (creators want integrated workflows, not 8 separate logins), but the underlying model dependencies were fragile. When Sora 2 died, every multi-modal integration that included Sora as the video layer broke simultaneously. The lesson for AI multi-modal: depend on architectures, not specific models. Or: build adapter abstractions so swapping a dead model for a live one is config-change rather than rebuild.',
    sources: [
      { label: 'r/SoraAi mention of related wrapper shutdowns', url: 'https://www.reddit.com/r/SoraAi/comments/1tcfwng/yopisora_bot_in_discord_has_shutdown/' },
    ],
    verificationStatus: 'DRAFT_REQUIRES_VERIFY',
    verificationNote: 'Existence of the integration is inferred from conversation context. If ElevenLabs never shipped a Sora wrapper and this is shorthand for something else, the record needs reframing.',
    tags: ['video', 'audio', 'wrapper', 'elevenlabs', 'sora'],
  },
  {
    slug: 'stable-video-diffusion-hosted',
    toolName: 'Stable Video Diffusion (hosted endpoint)',
    parentCompany: 'Stability AI',
    category: 'ai-video',
    categoryLabel: 'AI Video',
    status: 'deprecated',
    shutdownAnnounced: '',
    shutdownComplete: null,
    refundWindowClose: null,
    refundStatus: 'unknown',
    metaTitle: 'Stable Video Diffusion Hosted Endpoint — Status, Migration',
    metaDesc: 'Stability AI\'s hosted SVD endpoint has had inconsistent uptime. The open-weight model is still alive. Migration paths and refund flow.',
    summary: 'Stability AI released Stable Video Diffusion (SVD) as an open-weight model in November 2023 — one of the first generally-available video diffusion models. Stability also operated a hosted API. The open-weight model remains publicly available and actively used in the local AI video community. However, Stability AI\'s hosted API has had inconsistent uptime through 2024-2025 due to the company\'s funding turbulence. If you were using SVD via the hosted endpoint and it stopped working, this entry covers your migration options.',
    refundFlow: [
      'Contact Stability support via https://stability.ai/contact.',
      'Response time is reportedly slow due to restructuring; budget 14-30 days for a reply.',
      'For Stability Membership subscribers, the membership covers multiple models (SDXL, SD3, SVD) — if SVD is down but other models still work, partial refunds are unlikely. Pro-rated subscription credits are more common.',
    ],
    migration: {
      name: 'Two paths: run SVD locally (preserve exact model) OR migrate to hosted commercial alternative',
      whyClose: 'Local: open-weight SVD checkpoints are still on HuggingFace/Civit AI. With a 24GB GPU (3090/4090/A6000) you can run via ComfyUI/AUTOMATIC1111/InvokeAI. Hosted: Runway Gen-4 for photoreal, Pika 2.0 for stylization, Luma Ray-2 for lighting.',
      whatDiffers: 'Local preserves the exact model but loses hosted-API convenience. Hosted commercial alternatives are different models with different failure profiles.',
    },
    whatThisToolMeant: 'Stable Video Diffusion was the open-weight equivalent of Sora 1 — released around the same time, distributed under an open license. Its release was a major moment for the open-source AI video community. The model\'s failures (limited to ~4 seconds, weak motion priors, hand-anatomy issues) were known and accepted in exchange for the freedom of local control. Stability AI\'s broader funding crisis made the hosted endpoint unreliable, but the open-weight model is durable. This is the value of open-weight releases: the company can fail, the model lives on.',
    sources: [
      { label: 'Stability AI original SVD release', url: 'https://stability.ai/news/stable-video-diffusion-open-ai-video-model' },
      { label: 'HuggingFace model card (still active)', url: 'https://huggingface.co/stabilityai/stable-video-diffusion-img2vid-xt' },
    ],
    verificationStatus: 'DRAFT_REQUIRES_VERIFY',
    verificationNote: 'Hosted-endpoint specific status: deprecation is inferred from Stability AI\'s 2024 funding situation but not confirmed by an official announcement. Verify current state before publishing.',
    tags: ['video', 'stability-ai', 'open-weight', 'diffusion'],
  },
  {
    slug: 'inflection-pi',
    toolName: 'Inflection Pi',
    parentCompany: 'Inflection AI (Microsoft acquihire)',
    category: 'ai-agent',
    categoryLabel: 'AI Agents',
    status: 'deprecated',
    shutdownAnnounced: '2024-03-19',
    shutdownComplete: null,
    refundWindowClose: null,
    refundStatus: 'none',
    metaTitle: 'Inflection Pi Shutdown — What Happened, Migration to Claude',
    metaDesc: 'Microsoft acquihired Inflection in March 2024; Pi has had no active product team since. Closest replacement is Claude (for tone) or Copilot (for team).',
    summary: 'Inflection AI\'s Pi was a consumer chatbot designed as an "emotionally intelligent" alternative to ChatGPT. In March 2024, Microsoft acquihired the Inflection team — CEO Mustafa Suleyman became CEO of Microsoft AI. Inflection AI continued as a corporate-licensing entity, but the consumer Pi product stopped meaningful development. Pi was a free consumer product with no credits — no refund flow applies.',
    refundFlow: [
      'Not applicable. Pi was a free consumer product with no credits or subscriptions.',
    ],
    migration: {
      name: 'Claude (Anthropic) for tone, OR Microsoft Copilot for team-loyalty migration',
      whyClose: 'Claude is the closest substitute for Pi\'s emotionally-attuned conversational pattern. Microsoft Copilot is where the original Pi team went after the acquihire.',
      whatDiffers: 'Claude\'s tone is similar but different conversational pattern. Copilot is more task-oriented than emotionally-attuned.',
    },
    whatThisToolMeant: 'Inflection Pi was the most fully-realised attempt at "emotional AI" in the chatbot category — positioned as a conversational companion, not a coding or research tool. The team raised $1.3 billion to pursue this thesis. The Microsoft acquihire was a category signal: at scale, emotionally-attuned chatbot capability is a feature of general-purpose AI (Copilot, Gemini, Claude), not a standalone product. Inflection\'s pivot to corporate licensing post-acquihire confirms the consumer-emotional-chatbot positioning didn\'t sustain.',
    sources: [
      { label: 'Microsoft/Inflection acquihire announcement (March 2024)', url: 'https://blogs.microsoft.com/blog/2024/03/19/azure-inflection' },
    ],
    verificationStatus: 'DRAFT_REQUIRES_VERIFY',
    verificationNote: 'Current consumer-Pi-product status (still online vs fully retired) needs Joe to verify against the live Pi URL.',
    tags: ['agent', 'consumer-chatbot', 'inflection', 'microsoft'],
  },
  {
    slug: 'adept-ai',
    toolName: 'Adept ACT-1 / Workflow Agent',
    parentCompany: 'Adept AI Labs (Amazon acquihire)',
    category: 'ai-agent',
    categoryLabel: 'AI Agents',
    status: 'dead',
    shutdownAnnounced: '2024-06-26',
    shutdownComplete: null,
    refundWindowClose: null,
    refundStatus: 'closed',
    metaTitle: 'Adept AI Shutdown — Browser Agent Migration to Claude Computer Use',
    metaDesc: 'Amazon acquihired Adept in June 2024. Workflow agent product is dead. Migration to Claude Computer Use or OpenAI Operator.',
    summary: 'Adept AI Labs was developing "workflow agents" — AI models trained to operate desktop and browser applications. The flagship demonstration was ACT-1, which could complete multi-step office tasks. In June 2024, Amazon acquihired most of the Adept team; CEO David Luan and several co-founders joined Amazon. The remaining Adept entity wound down product development. For users who had been in Adept\'s enterprise pilots, the migration target is Anthropic\'s Claude Computer Use or general-purpose AI providers\' browser-agent capabilities.',
    refundFlow: [
      'Adept ACT-1 was sold primarily into enterprise pilot contracts, not consumer subscriptions.',
      'Refund situations are bilateral — enterprise customers should contact Adept\'s remaining commercial team via their original account manager.',
      'No public refund flow exists.',
    ],
    migration: {
      name: 'Claude Computer Use (Anthropic) OR OpenAI Operator',
      whyClose: 'For browser/web-based task automation: Claude Computer Use is the closest functional equivalent — same conceptual model. For desktop-app automation: OpenAI Operator or LangChain agent frameworks.',
      whatDiffers: 'Adept trained vision-language models specifically on UI-operation tasks at scale. Current substitutes are general-purpose models with computer-use scaffolding — they work but are less specialised.',
    },
    whatThisToolMeant: 'Adept was one of the most-watched agentic-AI companies pre-2024. The thesis — that the next major AI category would be agents operating real applications rather than chat — has proved correct, but Adept\'s specific bet on training a from-scratch vision-language model on UI tasks didn\'t survive contact with general-purpose models gaining computer-use capabilities natively. Every major lab (OpenAI, Anthropic, Google, Amazon) now ships agent-style features as extensions of their flagship models. Adept\'s positioning has been absorbed entirely. The lesson for enterprise: depend on capability categories, not specific company products.',
    sources: [
      { label: 'Amazon/Adept announcement', url: 'https://www.adept.ai/blog/adept-update' },
      { label: 'Adept ACT-1 original demonstration', url: 'https://www.adept.ai/blog/act-1' },
    ],
    verificationStatus: 'DRAFT_REQUIRES_VERIFY',
    verificationNote: 'Current status of remaining Adept entity needs verification. Some Adept assets were licensed back to enterprises post-acquihire.',
    tags: ['agent', 'workflow-automation', 'adept', 'amazon'],
  },
  {
    slug: 'gpt-3-davinci',
    toolName: 'GPT-3 davinci (and base model family)',
    parentCompany: 'OpenAI',
    category: 'ai-dev-tool',
    categoryLabel: 'AI Dev Tools',
    status: 'dead',
    shutdownAnnounced: '2024-01-04',
    shutdownComplete: '2024-01-04',
    refundWindowClose: null,
    refundStatus: 'closed',
    metaTitle: 'GPT-3 davinci Deprecation — Migration to GPT-4 (2024)',
    metaDesc: 'OpenAI deprecated GPT-3 davinci/curie/babbage/ada on Jan 4, 2024. Migration guide to gpt-4-turbo + code examples for chat-completion API.',
    summary: 'OpenAI\'s original GPT-3 base model family — davinci, curie, babbage, ada — was deprecated and removed from the OpenAI API on January 4, 2024. These were the original "completion" endpoints that powered the first wave of GPT-3 applications between 2020 and 2023. Most developers had migrated to gpt-3.5-turbo or gpt-4 before the deadline, but a long tail of legacy applications silently broke. There is no path to revive a GPT-3 davinci application; the migration target is gpt-4-turbo with prompt rewrites.',
    refundFlow: [
      'Not applicable. The OpenAI API is pay-as-you-go — no pre-paid credits or subscriptions tied to specific deprecated models.',
      'Costs simply stop accruing for the deprecated endpoints; you don\'t owe anything for unmade API calls.',
    ],
    migration: {
      name: 'gpt-4-turbo or gpt-4o (chat-completion API)',
      whyClose: 'GPT-4 is the direct successor for general-purpose language tasks. For high-volume / cost-sensitive applications, gpt-3.5-turbo is cheaper and still chat-style.',
      whatDiffers: 'GPT-3 davinci was a completion model (single prompt). GPT-4 is chat-completion (structured message arrays). Migration requires restructuring prompts, updating API signatures, re-testing outputs (stylistically different), and accepting 5-30× higher per-token cost.',
    },
    whatThisToolMeant: 'GPT-3 davinci was the foundation of the modern generative-AI era. Released as a paid API in June 2020, it powered most high-profile AI applications between 2020 and 2023: Jasper, Copy.ai, Notion AI, Sudowrite, hundreds of GPT-3 wrappers and chatbots, and the original ChatGPT (a fine-tune of GPT-3.5). Its deprecation closed a chapter of AI history. The completion-style API was harder to use safely (no built-in conversation structure, more prompt-injection surface area) but it was the model that proved generative AI\'s commercial viability. For developers nostalgic for the GPT-3 era, open-source ecosystems (LLaMA, Mistral, Mixtral) preserve the completion-style API pattern.',
    sources: [
      { label: 'OpenAI deprecations page (authoritative)', url: 'https://platform.openai.com/docs/deprecations' },
      { label: 'OpenAI\'s original GPT-3 release (2020)', url: 'https://openai.com/research/language-models-are-few-shot-learners' },
    ],
    verificationStatus: 'HIGH_CONFIDENCE',
    verificationNote: 'This is one of the most reliable entries — GPT-3 davinci deprecation is publicly documented on OpenAI\'s deprecation page and was widely covered.',
    tags: ['api', 'dev-tool', 'openai', 'gpt-3', 'language-model'],
  },
  {
    slug: 'dall-e-2',
    toolName: 'DALL-E 2',
    parentCompany: 'OpenAI',
    category: 'ai-image',
    categoryLabel: 'AI Image',
    status: 'deprecated',
    shutdownAnnounced: '2023-10-19',
    shutdownComplete: null,
    refundWindowClose: null,
    refundStatus: 'none',
    metaTitle: 'DALL-E 2 Deprecation — Migration to DALL-E 3 + GPT Image',
    metaDesc: 'OpenAI deprecated DALL-E 2 in 2023 when DALL-E 3 launched. Old API endpoints still work but no new development. Migration to DALL-E 3.',
    summary: 'DALL-E 2 was OpenAI\'s second-generation text-to-image model, released in April 2022 as the first commercial text-to-image API to ship at scale. When DALL-E 3 launched in October 2023, OpenAI moved active development to the new model. DALL-E 2 endpoints remain accessible via the API for backwards compatibility but receive no further improvements, and the standalone DALL-E 2 web interface (labs.openai.com) was retired.',
    refundFlow: [
      'Not applicable. The OpenAI API is pay-as-you-go — no pre-paid credits tied to specific deprecated models.',
      'For unused ChatGPT Plus credits that historically included DALL-E 2 generations, no separate refund applies because Plus pricing wasn\'t broken out per-model.',
    ],
    migration: {
      name: 'DALL-E 3 (via OpenAI API) or GPT Image (via ChatGPT)',
      whyClose: 'DALL-E 3 is the direct successor — same OpenAI text-to-image lineage, significantly improved prompt adherence and detail. GPT Image is the multimodal-output variant of GPT-4 that\'s replacing standalone DALL-E for many use cases.',
      whatDiffers: 'DALL-E 3 has better prompt adherence on long prompts but less stylization latitude than DALL-E 2. Higher cost per image. Different aspect-ratio support.',
    },
    whatThisToolMeant: 'DALL-E 2 was the model that made text-to-image generation a commercial category. Released in April 2022, it predated Midjourney\'s public launch and Stable Diffusion\'s open release by months. Its waitlist generated more demand than OpenAI had compute for, defining the "AI art" moment of 2022. The model\'s relatively low-resolution output (1024×1024) and inconsistent prompt adherence created the niche that Stable Diffusion and Midjourney would later fill with better control. DALL-E 2 isn\'t fully dead — its endpoints still respond — but it stopped being a serious choice when DALL-E 3 launched.',
    sources: [
      { label: 'OpenAI DALL-E 3 announcement (which marked the DALL-E 2 deprecation in practice)', url: 'https://openai.com/dall-e-3' },
      { label: 'OpenAI API deprecations page', url: 'https://platform.openai.com/docs/deprecations' },
    ],
    verificationStatus: 'HIGH_CONFIDENCE',
    verificationNote: 'DALL-E 3 release and the practical deprecation of DALL-E 2 is widely documented.',
    tags: ['image', 'dall-e', 'openai', 'text-to-image'],
  },
  {
    slug: 'bard-gemini-rebrand',
    toolName: 'Google Bard',
    parentCompany: 'Google',
    category: 'ai-agent',
    categoryLabel: 'AI Agents',
    status: 'dead',
    shutdownAnnounced: '2024-02-08',
    shutdownComplete: '2024-02-08',
    refundWindowClose: null,
    refundStatus: 'none',
    metaTitle: 'Google Bard Rebrand to Gemini — What Happened, Migration Guide',
    metaDesc: 'Google renamed Bard to Gemini on Feb 8, 2024. Same product, new name, integrated billing across Workspace + GCP. Migration is automatic.',
    summary: 'Google Bard launched as Google\'s ChatGPT competitor in March 2023. On February 8, 2024, Google rebranded the product entirely to "Gemini" — same underlying model family, new name, with the launch of Gemini Advanced (the paid tier, $19.99/mo). The Bard URL (bard.google.com) redirects to gemini.google.com. Existing user data and conversation history was migrated automatically.',
    refundFlow: [
      'Not applicable. Bard was a free product with no credits or subscriptions.',
      'For users now on Gemini Advanced ($19.99/mo) — standard Google subscription cancellation applies via your Google account billing settings.',
    ],
    migration: {
      name: 'Gemini (same product, automatic redirect)',
      whyClose: 'Bard and Gemini are the same product. Google migrated existing users without action required.',
      whatDiffers: 'Branding only at the consumer free tier. Gemini Advanced adds Gemini 1.5 Pro / 2.0 Pro models and Workspace integrations not available on free Bard.',
    },
    whatThisToolMeant: 'Bard\'s 18-month run (March 2023 → February 2024) coincided with the most chaotic period of consumer AI rollout. The product launched in response to ChatGPT, struggled with public quality perception (the famous launch-day demo error about James Webb Telescope wiped $100B from Google\'s market cap in a day), and was eventually folded into the broader Gemini brand to consolidate Google\'s AI product surface. The rebrand was strategy, not failure — Google decided Bard\'s brand equity wasn\'t worth preserving separately from the underlying Gemini model line.',
    sources: [
      { label: 'Google Bard → Gemini rebrand announcement', url: 'https://blog.google/products/gemini/bard-gemini-advanced-app' },
    ],
    verificationStatus: 'HIGH_CONFIDENCE',
    verificationNote: 'Rebrand date and scope are widely documented.',
    tags: ['chatbot', 'google', 'bard', 'gemini', 'rebrand'],
  },
  {
    slug: 'bing-chat-copilot-rebrand',
    toolName: 'Bing Chat',
    parentCompany: 'Microsoft',
    category: 'ai-agent',
    categoryLabel: 'AI Agents',
    status: 'dead',
    shutdownAnnounced: '2023-11-15',
    shutdownComplete: '2024-01-15',
    refundWindowClose: null,
    refundStatus: 'none',
    metaTitle: 'Bing Chat → Copilot Rebrand — Same Product, New Name',
    metaDesc: 'Microsoft renamed Bing Chat to "Microsoft Copilot" starting Nov 2023, complete by Jan 2024. Free product, automatic migration.',
    summary: 'Microsoft launched Bing Chat in February 2023, embedding GPT-4-based AI directly into the Bing search interface. In November 2023, Microsoft announced the rebrand to "Microsoft Copilot" — separating the AI capability from the Bing search brand. The transition was complete by January 2024. The product itself (GPT-4 + Bing search grounding) continued under the new name with expanded integrations across Windows 11, Edge, Microsoft 365, and standalone apps.',
    refundFlow: [
      'Not applicable. Bing Chat was a free product. The paid tier (Copilot Pro, $20/mo) was introduced after the rebrand, not before.',
    ],
    migration: {
      name: 'Microsoft Copilot (same product, automatic)',
      whyClose: 'Bing Chat and Copilot are the same product. Microsoft moved users without action required.',
      whatDiffers: 'Bing Chat was tied to Bing search and Edge browser. Copilot is now available standalone (copilot.microsoft.com), in Windows 11, in Microsoft 365 apps, and via mobile apps. The underlying capability is the same.',
    },
    whatThisToolMeant: 'Bing Chat\'s 9-month run was a strategic gambit by Microsoft to use AI to revive Bing search market share. The initial press impact was substantial (record Bing usage for several weeks in early 2023) but didn\'t convert into sustained market share gains against Google. The rebrand to Copilot reflects Microsoft\'s strategic conclusion that AI capability is more valuable as a product surface across their ecosystem than as a feature of one specific app. Bing search itself continues unchanged; only the AI branding moved.',
    sources: [
      { label: 'Microsoft Copilot rebrand announcement', url: 'https://blogs.microsoft.com/blog/2023/11/15/ignite-2023-ai-transformation' },
    ],
    verificationStatus: 'HIGH_CONFIDENCE',
    verificationNote: 'Rebrand date and scope are widely documented.',
    tags: ['chatbot', 'microsoft', 'bing', 'copilot', 'rebrand'],
  },
  {
    slug: 'claude-1-2',
    toolName: 'Claude 1 and Claude 2',
    parentCompany: 'Anthropic',
    category: 'ai-dev-tool',
    categoryLabel: 'AI Dev Tools',
    status: 'deprecated',
    shutdownAnnounced: '2024-07-01',
    shutdownComplete: null,
    refundWindowClose: null,
    refundStatus: 'closed',
    metaTitle: 'Claude 1 / Claude 2 Deprecation — Migration to Claude 3 Family',
    metaDesc: 'Anthropic deprecated Claude 1 and Claude 2 model strings via API. Migration to Claude 3 Haiku/Sonnet/Opus or Claude 3.5/4.x families.',
    summary: 'Anthropic\'s Claude 1 (released March 2023) and Claude 2 (released July 2023) model families were deprecated via API in 2024 as the Claude 3 family rolled out. The specific model identifiers (claude-1, claude-2.0, claude-2.1, claude-instant-1) stopped responding to new API calls; existing applications using those model strings broke at the deprecation deadline. Migration is a model-string change for most applications, plus prompt-format adjustments where Claude 3 behaves differently from Claude 2.',
    refundFlow: [
      'Not applicable. Anthropic API is pay-as-you-go — no pre-paid credits tied to specific deprecated models.',
      'For Claude.ai consumer subscribers, the consumer interface migrated automatically to newer models; no refund needed.',
    ],
    migration: {
      name: 'Claude 3 family (haiku / sonnet / opus) or current flagship',
      whyClose: 'Claude 3 is the direct successor model line. The API surface is similar (messages-style chat completion). Most migrations are a one-line model string change.',
      whatDiffers: 'Claude 3 has different prompt-style preferences (Anthropic publishes a prompt-engineering guide for the differences). Better instruction-following, better long-context handling, different pricing per token. Some Claude 2 prompt patterns that worked require minor adjustment.',
    },
    whatThisToolMeant: 'Claude 1 was Anthropic\'s first publicly-available API model — released to a small set of partners in March 2023, generally available later that year. Claude 2 brought 100K context window and significantly better reasoning. Together they established Anthropic as a serious alternative to OpenAI in the foundation-model market. Their deprecation in 2024 was orderly and well-communicated — typical Anthropic engineering culture, with multiple months of notice and a clean migration guide. Compare to less-organised deprecations from other labs.',
    sources: [
      { label: 'Anthropic API deprecation policy', url: 'https://docs.anthropic.com/en/docs/about-claude/model-deprecations' },
    ],
    verificationStatus: 'HIGH_CONFIDENCE',
    verificationNote: 'Anthropic publishes a deprecation policy page; specific model-string sunset dates are documented there.',
    tags: ['api', 'dev-tool', 'anthropic', 'claude', 'language-model'],
  },
  {
    slug: 'gpt-3-5-turbo-old-checkpoints',
    toolName: 'GPT-3.5 Turbo 0301 / 0613 / 1106 (specific dated checkpoints)',
    parentCompany: 'OpenAI',
    category: 'ai-dev-tool',
    categoryLabel: 'AI Dev Tools',
    status: 'dead',
    shutdownAnnounced: '2024-06-13',
    shutdownComplete: '2024-09-13',
    refundWindowClose: null,
    refundStatus: 'closed',
    metaTitle: 'GPT-3.5 Turbo Dated Checkpoints Deprecated — Migration Guide',
    metaDesc: 'OpenAI sunset gpt-3.5-turbo-0301, -0613, -1106 dated checkpoints in 2024. Apps pinning to those strings broke. Migration to gpt-3.5-turbo or gpt-4o-mini.',
    summary: 'OpenAI maintains both a generic `gpt-3.5-turbo` alias that always points to the current default checkpoint, and dated checkpoints (e.g., `gpt-3.5-turbo-0301`) that pin to specific model versions. Apps depending on dated checkpoints for output reproducibility broke when OpenAI sunset the older checkpoints during 2024. The generic alias kept working uninterrupted; only apps that explicitly pinned to dated versions were affected.',
    refundFlow: [
      'Not applicable. Pay-as-you-go API, no credits tied to deprecated checkpoints.',
    ],
    migration: {
      name: 'gpt-3.5-turbo (current alias) or gpt-4o-mini',
      whyClose: 'gpt-3.5-turbo alias still works — points to the latest GPT-3.5 checkpoint. gpt-4o-mini is the newer cheap-and-fast option with better quality at similar cost.',
      whatDiffers: 'If your app relied on reproducibility of a specific dated checkpoint (for evaluation harnesses, regression tests), the current alias breaks that contract. gpt-4o-mini is meaningfully more capable than GPT-3.5 but slightly more expensive.',
    },
    whatThisToolMeant: 'Dated-checkpoint pinning is the standard for production AI applications — you don\'t want your model behavior to drift silently when OpenAI updates the alias. The sunset of older dated checkpoints caused a quiet wave of production breakage in mid-2024 across applications that hadn\'t migrated to newer pins. The lesson for AI ops: monitor OpenAI\'s deprecation page proactively, don\'t pin to checkpoints near the deprecation horizon, and budget migration time well before the cutoff.',
    sources: [
      { label: 'OpenAI deprecations page', url: 'https://platform.openai.com/docs/deprecations' },
    ],
    verificationStatus: 'HIGH_CONFIDENCE',
    verificationNote: 'OpenAI publishes checkpoint deprecation dates publicly.',
    tags: ['api', 'dev-tool', 'openai', 'gpt-3-5', 'language-model'],
  },
  {
    slug: 'github-codex',
    toolName: 'OpenAI Codex (code model)',
    parentCompany: 'OpenAI',
    category: 'ai-dev-tool',
    categoryLabel: 'AI Dev Tools',
    status: 'dead',
    shutdownAnnounced: '2023-03-21',
    shutdownComplete: '2023-03-23',
    refundWindowClose: null,
    refundStatus: 'closed',
    metaTitle: 'OpenAI Codex Deprecation — Migration to GPT-4 Turbo',
    metaDesc: 'OpenAI sunset the standalone Codex code-completion model in March 2023, redirecting users to GPT-3.5 / GPT-4 for code tasks. GitHub Copilot continues separately.',
    summary: 'OpenAI Codex was the code-specialised model that originally powered GitHub Copilot (2021-2023). On March 21, 2023, OpenAI announced the discontinuation of the standalone Codex API, with shutdown two days later. The model was deprecated because GPT-3.5 and GPT-4 had become competitive at code generation while being more capable for general tasks — a single model became cheaper than maintaining two. GitHub Copilot itself continued operating; only the standalone Codex API was deprecated.',
    refundFlow: [
      'Not applicable. Codex was free during its public preview / pay-per-token after that — no pre-paid credits.',
    ],
    migration: {
      name: 'GPT-4 Turbo or GPT-4o for code generation; GitHub Copilot for IDE integration',
      whyClose: 'GPT-4 family is the direct successor for code-generation API use. GitHub Copilot is the productised IDE-integrated version that originally relied on Codex but has since moved to GPT-4 family models.',
      whatDiffers: 'GPT-4 is more general-purpose but the code-specific tuning that made Codex efficient on code tokens specifically is gone. Higher cost per token than Codex was. For pure code-completion use cases, the specialisation gap has been mostly closed by GPT-4 scale.',
    },
    whatThisToolMeant: 'Codex was the breakthrough model that proved AI could write meaningful code, not just autocomplete a few tokens. Released in 2021 (after the original Codex paper), it powered the first GitHub Copilot release. The 2023 deprecation marked the transition from specialised models (one per task) to general-purpose models (GPT-4 + careful prompting). The pattern repeats across AI: specialised models give way to scaled general models as the general models become competitive enough to amortise their cost across more use cases.',
    sources: [
      { label: 'OpenAI Codex deprecation announcement', url: 'https://openai.com/blog/gpt-4-api-general-availability' },
    ],
    verificationStatus: 'HIGH_CONFIDENCE',
    verificationNote: 'Codex deprecation date is well-documented.',
    tags: ['code', 'openai', 'codex', 'copilot', 'developer-tool'],
  },
  {
    slug: 'cohere-command-v1',
    toolName: 'Cohere Command (original / v1)',
    parentCompany: 'Cohere',
    category: 'ai-dev-tool',
    categoryLabel: 'AI Dev Tools',
    status: 'deprecated',
    shutdownAnnounced: '2024-04-01',
    shutdownComplete: null,
    refundWindowClose: null,
    refundStatus: 'closed',
    metaTitle: 'Cohere Command v1 Deprecation — Migration to Command R / R+',
    metaDesc: 'Cohere deprecated the original Command model in 2024 as Command R / R+ launched. Better RAG performance, similar API. Migration is mostly a model-string change.',
    summary: 'Cohere\'s original Command model (the generate-text endpoint) was deprecated through 2024 as the Command R and Command R+ family launched. Command R/R+ are designed for retrieval-augmented generation (RAG) workflows specifically, with significantly better long-context handling and citation accuracy than the original Command. The original Command endpoint was wound down on the standard Cohere deprecation timeline (typically 6-12 months notice).',
    refundFlow: [
      'Not applicable for trial users. Enterprise customers should reference their contract terms with Cohere\'s commercial team.',
    ],
    migration: {
      name: 'Command R / R+ (Cohere)',
      whyClose: 'Direct successor model family with the same Cohere API surface. R+ is significantly better on RAG and long-context tasks; R is the smaller / cheaper version.',
      whatDiffers: 'Different pricing per token, different prompt-style preferences (especially for RAG with documents). Better citation accuracy than original Command.',
    },
    whatThisToolMeant: 'Cohere positioned themselves from launch (2021) as the enterprise-focused alternative to OpenAI — privacy-friendly hosting, embeddings + reranking primitives, enterprise contract structure. The original Command model was their flagship for several years. The Command R+ launch in 2024 represented a strategic refocus on RAG workflows specifically — Cohere\'s bet that enterprise AI is mostly about retrieval over private documents, not zero-shot reasoning. The bet has been validated by market traction; Cohere is now a meaningful enterprise-AI vendor.',
    sources: [
      { label: 'Cohere Command R+ launch announcement', url: 'https://cohere.com/blog/command-r-plus-microsoft-azure' },
    ],
    verificationStatus: 'DRAFT_REQUIRES_VERIFY',
    verificationNote: 'Cohere\'s deprecation timeline for the original Command model needs verification against Cohere\'s API documentation. The exact sunset date of the original Command endpoint isn\'t a single publicly-marketed event.',
    tags: ['api', 'dev-tool', 'cohere', 'rag', 'enterprise'],
  },
  {
    slug: 'replit-ghostwriter',
    toolName: 'Replit Ghostwriter',
    parentCompany: 'Replit',
    category: 'ai-dev-tool',
    categoryLabel: 'AI Dev Tools',
    status: 'dead',
    shutdownAnnounced: '2024-01-30',
    shutdownComplete: '2024-02-29',
    refundWindowClose: null,
    refundStatus: 'none',
    metaTitle: 'Replit Ghostwriter → Replit AI Rebrand — What Changed',
    metaDesc: 'Replit renamed Ghostwriter to "Replit AI" in early 2024 with broader feature scope. Existing subscribers migrated automatically.',
    summary: 'Replit Ghostwriter was Replit\'s in-IDE AI coding assistant, launched in 2022 as a GitHub Copilot competitor. In January 2024, Replit rebranded the product to "Replit AI" with expanded scope — now covering not just code completion but also a chat interface, multi-file code generation, debugging assistance, and an agent mode for building entire apps from prompts. Existing Ghostwriter Pro subscribers were migrated to Replit AI Pro at the same price point.',
    refundFlow: [
      'Not applicable. Subscription migrated automatically at the same price; no refund situation arose for active subscribers.',
      'Users who had cancelled Ghostwriter before the rebrand were not auto-resubscribed.',
    ],
    migration: {
      name: 'Replit AI (same product, expanded scope)',
      whyClose: 'Replit AI includes everything Ghostwriter did, plus the new chat and agent features. Migration was automatic for active subscribers.',
      whatDiffers: 'New chat interface and agent mode are added capabilities, not replacements. Pricing structure shifted slightly (Pro / Teams / Enterprise tiers introduced).',
    },
    whatThisToolMeant: 'Ghostwriter\'s 18-month run paralleled the broader shift in AI coding tools from "autocomplete the next few tokens" (Copilot pre-2024) to "understand the project and generate multi-file changes" (post-2024). The rebrand to "Replit AI" was a positioning move to escape direct comparison with Copilot — Replit\'s strength is the integrated cloud IDE, not the AI alone. The product evolution paralleled Cursor\'s rise, Cody\'s expansion, and Copilot\'s own evolution into Copilot Workspace.',
    sources: [
      { label: 'Replit AI launch announcement', url: 'https://blog.replit.com/replit-ai' },
    ],
    verificationStatus: 'HIGH_CONFIDENCE',
    verificationNote: 'Rebrand timing and scope are documented in Replit\'s blog.',
    tags: ['code', 'replit', 'ide', 'developer-tool', 'rebrand'],
  },
  {
    slug: 'assemblyai-conformer-1',
    toolName: 'AssemblyAI Conformer-1',
    parentCompany: 'AssemblyAI',
    category: 'ai-audio',
    categoryLabel: 'AI Audio',
    status: 'deprecated',
    shutdownAnnounced: '2024-03-15',
    shutdownComplete: null,
    refundWindowClose: null,
    refundStatus: 'closed',
    metaTitle: 'AssemblyAI Conformer-1 Deprecated — Migration to Universal-1',
    metaDesc: 'AssemblyAI deprecated Conformer-1 as Universal-1 launched in 2024. Better accuracy, lower cost, same API. Migration is a model-string change.',
    summary: 'AssemblyAI\'s Conformer-1 was their flagship speech-recognition model from late 2023 through early 2024 — competitive with OpenAI\'s Whisper and Google\'s Speech-to-Text on accuracy benchmarks. In March 2024, AssemblyAI launched Universal-1, a newer architecture with meaningfully better accuracy on noisy audio, faster inference, and lower price per minute. Conformer-1 was placed in deprecated status with a 12-month sunset window.',
    refundFlow: [
      'Not applicable. AssemblyAI is pay-per-minute. No pre-paid credits tied to Conformer-1 specifically.',
      'For enterprise customers with fixed-price contracts pegged to Conformer-1 pricing, contract terms should reference the deprecation policy — work with your AssemblyAI account manager.',
    ],
    migration: {
      name: 'Universal-1 (AssemblyAI)',
      whyClose: 'Same API surface, same vendor, drop-in replacement for most use cases. Better accuracy on noisy / accented audio, lower cost.',
      whatDiffers: 'Different model behavior on edge cases — output might differ on identical audio. Universal-1 has stronger multilingual support; better speaker diarization. Pricing is per-minute but Universal-1 is cheaper.',
    },
    whatThisToolMeant: 'AssemblyAI built their commercial position on speech-recognition accuracy at competitive pricing — competing primarily with OpenAI Whisper (open-weight, run-it-yourself) and Google Speech-to-Text (more expensive, integrated with GCP). Conformer-1 was the model that established their commercial credibility in 2023. The Universal-1 release in 2024 was a generational step that consolidated their commercial position. The deprecation of Conformer-1 was orderly — typical of vertical-specialist AI vendors that depend on enterprise trust.',
    sources: [
      { label: 'AssemblyAI Universal-1 announcement', url: 'https://www.assemblyai.com/blog/universal-1-speech-recognition-model' },
    ],
    verificationStatus: 'DRAFT_REQUIRES_VERIFY',
    verificationNote: 'Specific deprecation timeline for Conformer-1 needs verification — Universal-1 launch is documented but exact Conformer-1 sunset date may vary by API tier.',
    tags: ['audio', 'speech-to-text', 'assemblyai', 'conformer', 'transcription'],
  },
  {
    slug: 'claude-instant-1',
    toolName: 'Claude Instant 1',
    parentCompany: 'Anthropic',
    category: 'ai-dev-tool',
    categoryLabel: 'AI Dev Tools',
    status: 'dead',
    shutdownAnnounced: '2024-03-01',
    shutdownComplete: '2024-09-01',
    refundWindowClose: null,
    refundStatus: 'closed',
    metaTitle: 'Claude Instant 1 Deprecation — Migration to Claude 3 Haiku',
    metaDesc: 'Anthropic deprecated Claude Instant 1 in 2024. Migration to Claude 3 Haiku — faster, cheaper, smarter. Drop-in replacement for most apps.',
    summary: 'Claude Instant 1 was Anthropic\'s fast / cheap variant of Claude 1, designed for high-throughput applications where Claude 1\'s reasoning depth was overkill. The model identifier `claude-instant-1` was deprecated in 2024 as Claude 3 Haiku launched with better performance, lower cost, and the same speed profile. Most apps using Claude Instant migrated to Haiku with a one-line model string change.',
    refundFlow: [
      'Not applicable. Anthropic API is pay-as-you-go — no pre-paid credits tied to deprecated models.',
    ],
    migration: {
      name: 'Claude 3 Haiku (Anthropic)',
      whyClose: 'Direct successor for the fast/cheap tier. Better quality, lower cost, similar latency profile.',
      whatDiffers: 'Different prompt-style preferences (Anthropic\'s Claude 3 prompt-engineering guide covers the differences). Slightly better instruction-following.',
    },
    whatThisToolMeant: 'Claude Instant 1 served the segment of API customers running high-QPS workloads — chatbots, summarisation pipelines, batch inference — where every cent per million tokens matters. Its successor Claude 3 Haiku, then Claude Haiku 4.5, continued this positioning. The deprecation was orderly and well-communicated, typical of Anthropic\'s engineering discipline.',
    sources: [
      { label: 'Anthropic API deprecation policy', url: 'https://docs.anthropic.com/en/docs/about-claude/model-deprecations' },
    ],
    verificationStatus: 'HIGH_CONFIDENCE',
    verificationNote: 'Anthropic publishes deprecation dates on the API deprecation policy page.',
    tags: ['api', 'dev-tool', 'anthropic', 'claude-instant', 'language-model'],
  },
  {
    slug: 'text-embedding-ada-002',
    toolName: 'text-embedding-ada-002',
    parentCompany: 'OpenAI',
    category: 'ai-dev-tool',
    categoryLabel: 'AI Dev Tools',
    status: 'deprecated',
    shutdownAnnounced: '2024-01-25',
    shutdownComplete: null,
    refundWindowClose: null,
    refundStatus: 'none',
    metaTitle: 'text-embedding-ada-002 Deprecation — Migration to text-embedding-3',
    metaDesc: 'OpenAI deprecated text-embedding-ada-002 in 2024 with text-embedding-3-small/large. Migration requires re-embedding existing vector stores.',
    summary: 'OpenAI\'s text-embedding-ada-002 was the de-facto standard embedding model from late 2022 through 2023, powering most RAG (retrieval-augmented generation) applications. In January 2024, OpenAI released the text-embedding-3 family (small and large variants) with significantly better quality, lower cost, and configurable output dimensions. Ada-002 was placed in deprecated status. The endpoint still responds but receives no further improvements, and apps using ada-002 will benefit from migration.',
    refundFlow: [
      'Not applicable. OpenAI API is pay-as-you-go — no pre-paid credits tied to embedding models.',
    ],
    migration: {
      name: 'text-embedding-3-small or text-embedding-3-large',
      whyClose: 'Direct successor models from the same family. -3-small is faster + cheaper than ada-002; -3-large is better quality.',
      whatDiffers: 'Different embedding dimensions (1536 default for ada-002 vs 1536/3072 for -3 family). Migration requires re-embedding your entire vector store — embeddings are not cross-model compatible. Output quality on retrieval tasks is meaningfully better with -3.',
    },
    whatThisToolMeant: 'text-embedding-ada-002 was the embedding model that made consumer-tier RAG economically viable. Released in late 2022 with a 100x cost reduction over the prior `text-search-davinci-001`, it triggered the wave of "chat with your documents" SaaS products in 2023. Its successor (text-embedding-3) is meaningfully better but the ecosystem cost to re-embed every existing vector store was substantial — many apps still run ada-002 in production well into 2025.',
    sources: [
      { label: 'OpenAI text-embedding-3 announcement', url: 'https://openai.com/blog/new-embedding-models-and-api-updates' },
      { label: 'OpenAI API deprecations page', url: 'https://platform.openai.com/docs/deprecations' },
    ],
    verificationStatus: 'HIGH_CONFIDENCE',
    verificationNote: 'text-embedding-3 release and ada-002 deprecation are widely documented.',
    tags: ['api', 'dev-tool', 'openai', 'embedding', 'rag'],
  },
  {
    slug: 'whisper-api-v1',
    toolName: 'Whisper API v1 (large-v1)',
    parentCompany: 'OpenAI',
    category: 'ai-audio',
    categoryLabel: 'AI Audio',
    status: 'deprecated',
    shutdownAnnounced: '2023-11-15',
    shutdownComplete: null,
    refundWindowClose: null,
    refundStatus: 'none',
    metaTitle: 'OpenAI Whisper v1 Deprecation — Migration to whisper-1 (latest)',
    metaDesc: 'OpenAI deprecated the original Whisper large-v1 endpoint in 2023 as Whisper large-v2 / v3 launched. The hosted `whisper-1` API alias still works.',
    summary: 'OpenAI released the Whisper API in March 2023, exposing the speech-recognition model that the open-source community had been running locally for months. The original "large-v1" checkpoint was the only version available via the hosted API at first. As newer Whisper checkpoints (large-v2, large-v3) released through 2023, the API alias `whisper-1` was updated to point at the latest checkpoint. Apps pinning to specific dated checkpoints saw breakage; apps using the alias kept working.',
    refundFlow: [
      'Not applicable. Pay-per-minute API, no pre-paid credits.',
    ],
    migration: {
      name: 'whisper-1 alias (still active, points to latest)',
      whyClose: 'OpenAI maintains the `whisper-1` alias to always point at the current best Whisper checkpoint. Most apps using the alias never broke.',
      whatDiffers: 'If your app pinned to a specific dated checkpoint, you needed to migrate to the alias. Newer Whisper versions have meaningfully better non-English support and reduced hallucinations on silent audio.',
    },
    whatThisToolMeant: 'Whisper was a watershed moment for speech-recognition — the first time a state-of-the-art STT model was both open-weight and exposed via affordable hosted API. The original release powered most AI transcription tools in 2023. The model continues to be relevant in 2026 although the hosted API has been augmented by newer models (gpt-4o-transcribe, GPT-4o-mini-transcribe) that improve on Whisper\'s blind spots (accented speech, silent passages, code-switching).',
    sources: [
      { label: 'OpenAI Whisper API announcement (March 2023)', url: 'https://openai.com/blog/introducing-chatgpt-and-whisper-apis' },
      { label: 'OpenAI deprecations page', url: 'https://platform.openai.com/docs/deprecations' },
    ],
    verificationStatus: 'DRAFT_REQUIRES_VERIFY',
    verificationNote: 'The exact deprecation status of the dated Whisper checkpoint endpoints (vs the still-active alias) needs Joe to verify against the current deprecation page. The `whisper-1` alias is still active as of training cutoff.',
    tags: ['audio', 'speech-to-text', 'openai', 'whisper', 'transcription'],
  },
  {
    slug: 'adobe-firefly-image-1',
    toolName: 'Adobe Firefly Image 1',
    parentCompany: 'Adobe',
    category: 'ai-image',
    categoryLabel: 'AI Image',
    status: 'deprecated',
    shutdownAnnounced: '2024-10-01',
    shutdownComplete: null,
    refundWindowClose: null,
    refundStatus: 'none',
    metaTitle: 'Adobe Firefly Image 1 Deprecation — Migration to Firefly Image 2/3',
    metaDesc: 'Adobe deprecated Firefly Image 1 when Image 2 launched late 2024. Migration to Firefly Image 3 via Creative Cloud — same UX, meaningfully better output.',
    summary: 'Adobe Firefly Image 1 was the first commercial text-to-image model trained entirely on Adobe Stock + public-domain content, making it commercially-safe for advertising and editorial work. When Firefly Image 2 launched in late 2024 with significantly better prompt adherence and photoreal output, Firefly Image 1 was placed in deprecated status. The model identifier still works via legacy API integrations but receives no further training improvements.',
    refundFlow: [
      'Not applicable. Firefly is bundled into Adobe Creative Cloud subscriptions; there is no separate per-model billing to refund.',
      'For Adobe Express / Creative Cloud subscribers using Firefly Image 1 specifically, contact Adobe support — they may offer subscription credits if you specifically subscribed for Image 1\'s commercial-safety guarantee that Image 2/3 inherits anyway.',
    ],
    migration: {
      name: 'Adobe Firefly Image 3 (default in Creative Cloud)',
      whyClose: 'Direct successor inside the same Creative Cloud subscription. Same commercial-safe training data thesis (Adobe Stock + public domain), significantly better prompt adherence and photoreal output.',
      whatDiffers: 'Different model behavior on edge cases — output style for identical prompts may differ. Image 3 has stronger composition control and reference-image input. Image 1 had a softer, more painterly default style that some users preferred for editorial work.',
    },
    whatThisToolMeant: 'Firefly Image 1 was Adobe\'s commercial answer to Midjourney + DALL-E — the first text-to-image model with a defensible commercial-safety story for advertising agencies and editorial publishers. The "trained on Adobe Stock + public domain only" claim addressed a real legal anxiety in 2023-2024 about AI image generators trained on scraped content. Image 2 and Image 3 preserved that commercial-safety positioning and built on it. The model itself is gone but the strategic positioning continues.',
    sources: [
      { label: 'Adobe Firefly Image 2 announcement (Adobe MAX 2023)', url: 'https://blog.adobe.com/en/publish/2023/10/10/adobe-firefly-image-2-now-available' },
    ],
    verificationStatus: 'HIGH_CONFIDENCE',
    verificationNote: 'Firefly Image 2 release and the practical deprecation of Image 1 is well-documented in Adobe\'s product announcements.',
    tags: ['image', 'firefly', 'adobe', 'commercial-safe'],
  },
  {
    slug: 'midjourney-v5',
    toolName: 'Midjourney v5 (and earlier)',
    parentCompany: 'Midjourney',
    category: 'ai-image',
    categoryLabel: 'AI Image',
    status: 'deprecated',
    shutdownAnnounced: '2024-02-10',
    shutdownComplete: null,
    refundWindowClose: null,
    refundStatus: 'none',
    metaTitle: 'Midjourney v5 Deprecation — Migration to v6 / v7',
    metaDesc: 'Midjourney deprecated v5 when v6 launched February 2024. The `--v 5` flag still works on legacy generations but receives no improvements.',
    summary: 'Midjourney v5 was the model that established Midjourney\'s commercial dominance in 2023, with the photoreal output quality that made it the default text-to-image tool for marketing agencies and creator content. When v6 launched in February 2024 with major improvements to text rendering, prompt adherence, and finer detail control, v5 was placed in legacy status. The `--v 5` flag is still accessible in the Discord interface but receives no further model improvements; v7 is the current default.',
    refundFlow: [
      'Not applicable. Midjourney subscriptions are not version-locked; the same subscription covers all available model versions.',
      'For users who specifically valued v5\'s aesthetic and find v6/v7 too different, Midjourney support may offer credit adjustments — but the formal policy doesn\'t guarantee them.',
    ],
    migration: {
      name: 'Midjourney v7 (current default) or v6 (transitional)',
      whyClose: 'Same subscription, same interface, drop-in replacement. v7 has the strongest prompt adherence and text-rendering of any consumer image model.',
      whatDiffers: 'v5\'s photoreal output had a distinctive softness that many users associated with the "Midjourney look." v6 and v7 are more literal interpretations of prompts with sharper detail. For users who built workflows around v5\'s style, the migration requires prompt re-engineering.',
    },
    whatThisToolMeant: 'Midjourney v5 was the model that won the commercial creative market in 2023. Its output quality was the reason Adobe rushed Firefly Image 2 + 3 to market and OpenAI accelerated DALL-E 3 — the competition all calibrated against v5\'s aesthetic. The v5 deprecation as default model marked the moment Midjourney stopped being a "creative cool" tool and became infrastructure that thousands of agencies depend on. v7 continues the lineage with better tools but less of the distinctive style that built the brand.',
    sources: [
      { label: 'Midjourney v6 announcement', url: 'https://www.midjourney.com/news' },
    ],
    verificationStatus: 'HIGH_CONFIDENCE',
    verificationNote: 'v6 release and v5\'s practical deprecation are widely documented in Midjourney\'s Discord and on the news page.',
    tags: ['image', 'midjourney', 'discord', 'creative'],
  },
  {
    slug: 'chatgpt-plugins-marketplace',
    toolName: 'ChatGPT Plugins (marketplace)',
    parentCompany: 'OpenAI',
    category: 'ai-agent',
    categoryLabel: 'AI Agents',
    status: 'dead',
    shutdownAnnounced: '2024-03-19',
    shutdownComplete: '2024-04-09',
    refundWindowClose: null,
    refundStatus: 'closed',
    metaTitle: 'ChatGPT Plugins Marketplace Shutdown — Migration to Custom GPTs',
    metaDesc: 'OpenAI shut down the original ChatGPT Plugins marketplace in April 2024, replaced by Custom GPTs (GPT Store). Migration guide for plugin developers + users.',
    summary: 'ChatGPT Plugins was OpenAI\'s first attempt at a third-party developer marketplace inside ChatGPT, launched in March 2023. Developers could ship plugins that extended ChatGPT with custom tools (Wolfram Alpha, Expedia, OpenTable, etc.). In November 2023 OpenAI announced the successor — Custom GPTs + the GPT Store — and the original plugins marketplace was officially deprecated on March 19, 2024 with shutdown completed April 9, 2024. Plugin developers had ~5 months notice to migrate.',
    refundFlow: [
      'Not applicable for ChatGPT Plus subscribers (no separate per-plugin billing).',
      'For Plugin developers with active enterprise contracts, individual contract terms applied — direct contact with OpenAI partner support.',
    ],
    migration: {
      name: 'Custom GPTs / GPT Store',
      whyClose: 'Direct successor and OpenAI\'s explicit migration path. Same tool-use capability, expanded scope (custom system prompts + knowledge files + actions). GPT Store provides discoverability that the plugin marketplace lacked.',
      whatDiffers: 'Custom GPTs are richer (system prompt + files + actions vs plugin\'s action-only API). Better discoverability via GPT Store. But: GPT revenue share was announced post-launch and adoption has been slower than the original plugin ecosystem hoped for.',
    },
    whatThisToolMeant: 'ChatGPT Plugins was OpenAI\'s thesis that LLMs would be the new "operating system" and third-party tools would be apps. The marketplace launched with high developer interest but never gained the consumer traction OpenAI hoped for — most ChatGPT users never enabled plugins. The Custom GPT pivot in late 2023 was an acknowledgment that user-facing customization (vs developer-facing tools) was the better product surface. The deprecation was orderly and well-communicated.',
    sources: [
      { label: 'OpenAI Plugins deprecation announcement', url: 'https://help.openai.com/en/articles/8988022-winding-down-the-chatgpt-plugins-beta' },
    ],
    verificationStatus: 'HIGH_CONFIDENCE',
    verificationNote: 'OpenAI documented this shutdown clearly in their help center.',
    tags: ['agent', 'openai', 'plugins', 'chatgpt', 'marketplace'],
  },
  {
    slug: 'github-copilot-labs',
    toolName: 'GitHub Copilot Labs',
    parentCompany: 'GitHub (Microsoft)',
    category: 'ai-dev-tool',
    categoryLabel: 'AI Dev Tools',
    status: 'dead',
    shutdownAnnounced: '2023-12-15',
    shutdownComplete: '2024-02-15',
    refundWindowClose: null,
    refundStatus: 'none',
    metaTitle: 'GitHub Copilot Labs Deprecation — Migration to Copilot Chat',
    metaDesc: 'GitHub deprecated Copilot Labs (the experimental extension) in early 2024 as Copilot Chat and Copilot Workspace absorbed its features.',
    summary: 'GitHub Copilot Labs was an experimental VS Code extension that shipped features GitHub was testing for inclusion in the main Copilot product — code explanation, code translation between languages, brushstroke-style code modifications. The extension was deprecated in early 2024 as Copilot Chat (released late 2023) and Copilot Workspace (preview in 2024) absorbed its functionality into the main Copilot product. The Labs extension can no longer be installed; existing installs stopped working at end-of-life.',
    refundFlow: [
      'Not applicable. Copilot Labs was a free extension bundled with Copilot subscriptions — no separate billing.',
    ],
    migration: {
      name: 'GitHub Copilot Chat (or Copilot Workspace for project-level work)',
      whyClose: 'Direct successor in the same Copilot ecosystem. Copilot Chat handles all the explanation/translation/modification features Labs had, integrated into the main IDE experience.',
      whatDiffers: 'Copilot Chat is more conversational; Labs was menu-driven. Some Labs-specific features (the original brushstroke metaphor for inline modifications) don\'t have direct equivalents but the underlying capability is covered.',
    },
    whatThisToolMeant: 'Copilot Labs was the testing ground that proved chat + multi-file editing + explain-code were the right product surfaces for AI coding tools. The features tested in Labs became the templates for Copilot Chat, Cursor, Cody, Codeium, and every modern AI coding tool. The deprecation marked the maturation of AI coding — what was experimental in 2022 became table stakes in 2024.',
    sources: [
      { label: 'GitHub Copilot Labs deprecation', url: 'https://docs.github.com/en/copilot' },
    ],
    verificationStatus: 'HIGH_CONFIDENCE',
    verificationNote: 'Deprecation is documented in GitHub\'s product announcements.',
    tags: ['code', 'github', 'microsoft', 'copilot', 'developer-tool'],
  },
  {
    slug: 'stable-diffusion-xl-hosted',
    toolName: 'Stable Diffusion XL (Stability AI hosted)',
    parentCompany: 'Stability AI',
    category: 'ai-image',
    categoryLabel: 'AI Image',
    status: 'deprecated',
    shutdownAnnounced: '',
    shutdownComplete: null,
    refundWindowClose: null,
    refundStatus: 'unknown',
    metaTitle: 'Stable Diffusion XL Hosted Endpoint — Status + Migration',
    metaDesc: 'Stability AI\'s hosted SDXL endpoint has had inconsistent uptime through 2024-2025. The open-weight SDXL model is alive and well; only the hosted API is questionable.',
    summary: 'Stable Diffusion XL (SDXL) was released by Stability AI in July 2023 as an open-weight model and a hosted API. The open-weight model became the foundation of the local AI image community (Automatic1111, ComfyUI, InvokeAI, all SDXL-based). The hosted API endpoint had inconsistent uptime through 2024-2025 due to Stability AI\'s broader funding turbulence. The hosted endpoint may have been quietly wound down; verify before relying on it.',
    refundFlow: [
      'Contact Stability AI support at https://stability.ai/contact for any unspent membership credits.',
      'Response time is reportedly slow due to restructuring; budget 14-30 days for a reply.',
    ],
    migration: {
      name: 'Run SDXL locally via ComfyUI / Automatic1111 — OR migrate to Replicate / fal.ai hosted SDXL',
      whyClose: 'The open-weight SDXL model is unchanged and freely available. Replicate and fal.ai both host SDXL as managed API services with reliable uptime, identical model outputs.',
      whatDiffers: 'Local: requires a 12GB+ GPU and ComfyUI knowledge. Replicate / fal.ai: paid per-generation but reliable. Stability\'s hosted endpoint was bundled with Stability Membership — switching to Replicate is à-la-carte pricing.',
    },
    whatThisToolMeant: 'SDXL was Stability AI\'s answer to DALL-E 3 — an open-weight model with output quality competitive with the leading closed models. The open release in July 2023 changed the local AI image landscape permanently (every local image tool standardized on SDXL as the base architecture). Stability AI\'s subsequent funding issues didn\'t kill SDXL itself — it killed the company\'s ability to run hosted infrastructure reliably. The model lives on in every local AI image workflow.',
    sources: [
      { label: 'Stability AI SDXL release', url: 'https://stability.ai/news/stable-diffusion-sdxl-1-announcement' },
      { label: 'HuggingFace model card', url: 'https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0' },
    ],
    verificationStatus: 'DRAFT_REQUIRES_VERIFY',
    verificationNote: 'Hosted-endpoint specific status needs verification. The open-weight SDXL model is verifiably alive and well; only the Stability-hosted API uptime is the question.',
    tags: ['image', 'stability-ai', 'sdxl', 'open-weight'],
  },
  {
    slug: 'codex-completions-deprecated',
    toolName: 'OpenAI text-davinci-003 (completions endpoint)',
    parentCompany: 'OpenAI',
    category: 'ai-dev-tool',
    categoryLabel: 'AI Dev Tools',
    status: 'dead',
    shutdownAnnounced: '2024-01-04',
    shutdownComplete: '2024-01-04',
    refundWindowClose: null,
    refundStatus: 'none',
    metaTitle: 'text-davinci-003 Deprecation — Migration to GPT-4 ChatCompletion',
    metaDesc: 'OpenAI deprecated text-davinci-003 (last of the GPT-3.5 completions endpoints) in January 2024. Migration to gpt-3.5-turbo or gpt-4 chat-completion API.',
    summary: 'text-davinci-003 was the most-capable completion-style model in OpenAI\'s GPT-3.5 family, released November 2022 and the default model for many production applications through 2023. It was deprecated on January 4, 2024 along with the broader GPT-3 base model family (curie, babbage, ada). Applications pinning to text-davinci-003 broke at the deprecation deadline; the migration path was to the chat-completion API with gpt-3.5-turbo or gpt-4.',
    refundFlow: [
      'Not applicable. OpenAI API is pay-as-you-go — no pre-paid credits tied to deprecated models.',
    ],
    migration: {
      name: 'gpt-3.5-turbo (for cost-equivalent) or gpt-4-turbo / gpt-4o (for quality)',
      whyClose: 'Direct functional successors. gpt-3.5-turbo is approximately cost-equivalent to text-davinci-003 was. gpt-4 family is more capable at higher cost.',
      whatDiffers: 'Different API: chat-completion (messages array) vs completion (single prompt). Different prompt-style preferences. Different tokenizer (cl100k_base vs p50k_base) so token counts and pricing differ. Behavioral differences require prompt re-engineering for most applications.',
    },
    whatThisToolMeant: 'text-davinci-003 was the workhorse model for most production AI applications in 2023 — Jasper, Copy.ai, Notion AI, hundreds of GPT-3.5 wrappers and SaaS tools. Its deprecation marked the end of the completion-style API as the default; everything since has standardized on chat-completion. The deprecation was widely covered and most applications migrated cleanly before the deadline, but a long tail of legacy applications silently broke.',
    sources: [
      { label: 'OpenAI deprecations page', url: 'https://platform.openai.com/docs/deprecations' },
      { label: 'text-davinci-003 release blog', url: 'https://openai.com/blog/' },
    ],
    verificationStatus: 'HIGH_CONFIDENCE',
    verificationNote: 'Documented in OpenAI\'s deprecation page.',
    tags: ['api', 'dev-tool', 'openai', 'gpt-3-5', 'language-model'],
  },
];

export function getShutdown(slug: string): ShutdownRecord | undefined {
  return SHUTDOWNS.find((s) => s.slug === slug);
}

export function getRelatedShutdowns(slug: string, limit = 4): ShutdownRecord[] {
  const current = getShutdown(slug);
  if (!current) return [];
  return SHUTDOWNS
    .filter((s) => s.slug !== slug && s.category === current.category)
    .slice(0, limit);
}
